### ISSUE TITLE
Merge Iconify and text Block

### ISSUE THREAD

**Issue by andrewfstratton** [andrewfstratton/quando#123]
i.e. Inventor Text block could have a menu for normal/iconify/italic/bold
Possibly in extras - maybe show the style applied in the actual text :)

Clarification - text Block is an Inventor block - with a small amount of text.  it may be entered using a text box - but it is inventor entered, not end user...

**Comment by balraj-johal** [comment]
Could be done using the multiline text editor @DirectK made? Or just w extras.

**Comment by andrewfstratton** [comment]
IBM Cloud [toolchain](https://console.bluemix.net/devops/toolchains/2cef73e4-1589-4b6d-ad52-2bba05849746?env_id=ibm%3Ayp%3Aeu-gb "quando-feb24b"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/c7530d05-4a5f-4670-8c8f-edabfb8207a0?env_id=ibm%3Ayp%3Aeu-gb "quando-feb24b") deployed [quando](https://github.com/andrewfstratton/quando/releases/tag/deploy-ibm-yp-eu-gb-a.stratton-sheffield.ac.uk-dev-20190719-102620 "deploy-ibm-yp-eu-gb-a.stratton-sheffield.ac.uk-dev-20190719-102620") to [dev](https://console.bluemix.net/apps/0e3846af-b18d-4b6e-9456-d83a4afc53b2?env_id=ibm:yp:eu-gb "ibm:yp:eu-gb:a.stratton@sheffield.ac.uk:dev"), including commits e0496f15994ce2e3d6294d0d81285708da410c5d, d8ac8aea5c4cc1e291f319fc8aec85ed61863843, 356450df384a1e6039e8d170b3f855128c9901e8
