### ISSUE TITLE
Design way to discover IP address of Nao

### ISSUE THREAD

**Issue by andrewfstratton** [andrewfstratton/quando#167]
**Plan**

1. Allow button press then IP entry from inventor block (in extras?) and through hub/deploy script choice
2. Save all IP addresses to database as well
3. When running client, check the IP addresses and use the first found (!)

Extension - Extras could allow limiting connection to a specific mac address/robot

Suggestion - Inventor should have a control panel that shows the current status of 'things'/devices.
- or don't bother - create a script?!
---

Separate issues:

1. Discovery - *First time*
2. Reload - *find again after discovery*

**Discovery**

Methods can be listed by reliability and usability:

| Reliability | Usability | Ease of development | Description |
| --- | --- | --- | --- |
| High | low | High | Chest button press reporting IP Address |
| medium | High / low<sup>1</sup> | medium | Last IP address used |
| medium / low<sup>2</sup> | High | low | Scan using arp -a |
| low | High | low | Scan using browser |

*<sup>1</sup> when not previously accessed*
*<sup>2</sup> for wifi*

Note: mac address can be used to uniquely identify Nao 
- and the prefix identifies the manufacturer

Options include:

- Press button on Nao (this is the fallback - it always works - but is slow)
- **Cache all the ip addresses where the Nao has been seen**
  - **store in the db**
    - don't need to check 65,000
    - plus, can update ip from anywhere on the same subnet/s
    - or from inventor instead of client
    - should only need to press the chest button once for a network (?!)
      - actually, the Nao can hop between ip addresses on wifi - but once these are entered, it should be possible to hop between them automatically
- Use arp -a and grep for mac address
  - Only works on locally deployed (or possibly hub)
  - Only works when pinged beforehand - so
    - Pings the all subnet IPs (c2 seconds) first
- Scan all the IPs for a Nao response
  - This may be quite slow from browser

**Comment by balraj-johal** [comment]
trying arp, going alright uno

**Comment by andrewfstratton** [comment]
btw - did you know that there is an arp based npm package for discovering
devices?
