### ISSUE TITLE
Enable nodemon in dockerised Quando to respond to local changes

### ISSUE THREAD

**Issue by boardfish** [andrewfstratton/quando#178]
Again, just flagging up that I'll be doing this soon. I'll need to write a slightly different Dockerfile that mounts in the whole directory and watches it with Nodemon - [explanation for those new to Docker](https://medium.com/better-programming/docker-in-development-with-nodemon-d500366e74df).

**Comment by andrewfstratton** [comment]
We need to discuss this - since Quando is mainly deployed locally.

**Comment by boardfish** [comment]
I don't think that should make a difference as to whether or not we do this - yes, containerisation is primarily for deployment on platforms like Kubernetes, but it's also important to make sure that everyone's working from the same development environment. It eliminates the concept of "works on my machine" and also isn't all that tough to implement with the right knowledge.

I've already done half the work [in this PR](https://github.com/andrewfstratton/quando/pull/177) - I just need to make sure it runs Nodemon instead, and mounts the current folder in as a volume.

**Comment by boardfish** [comment]
Rescoping this issue for the above.
