### ISSUE TITLE
Reorder Inventor blocks in menu

### ISSUE THREAD

**Issue by andrewfstratton** [andrewfstratton/quando#188]
New order to be split into:
- Main block
- Simple/output
- Choices
- API call generation
- [x] move 'raw' to end.
- [x] change colour of 'raw'.
- [x] move block-javascript to the end & make it grey.
- [x] move 'choice' after the menu (menu-toggle-show on toggle-choice).
- [x] move 'extras' before/after the menu-choice & change colour.
- [x] move 'hover' to near the end.

**Comment by chungyanlee** [comment]
![inventor blocks](https://user-images.githubusercontent.com/36131565/68300150-2048f200-0095-11ea-9142-4ae209fb5f9f.jpg)

**Comment by andrewfstratton** [comment]
Done or not essential (further re-ordering)
