### ISSUE TITLE
add "joystick" like value mapping block

### ISSUE THREAD

**Issue by balraj-johal** [andrewfstratton/quando#423]
block design clip:

[{"block_type":"inventor-function-block","values":{"_quando_block_type_":"","class":"quando-advanced","box_row1":"yes","_quando_box_name1_":"box","box_row2":"no","_quando_box_name2_":"","generator":"raw","library":"","function":""},"boxes":[{"id":"_quando_inventor_row1_","box":[{"block_type":"inventor-icon","values":{"icon":"⚡"}},{"block_type":"inventor-text","values":{"text":"map to joystick","extras":"hidden","iconify":"false","bold":"false","italic":"false"}},{"block_type":"inventor-icon","values":{"icon":"🕹"}},{"block_type":"inventor-icon","values":{"icon":"⚡"}},{"block_type":"inventor-extras","values":{"extras_name":"extras"},"boxes":[{"id":"box","box":[{"block_type":"inventor-text","values":{"text":"with deadzone of","extras":"hidden","iconify":"false","bold":"false","italic":"false"}},{"block_type":"inventor-input","values":{"input":"deadzone","default":"5","placeholder":"","extras":"hidden","type":"text","number_min":"0","number_max":"100","number_width":"4","encode":"normal"}},{"block_type":"inventor-text","values":{"text":"%","extras":"hidden","iconify":"false","bold":"false","italic":"false"}}]}]}]},{"id":"_quando_inventor_row2_"},{"id":"_quando_inventor_row3_"},{"id":"_quando_inventor_generator_"}]}]

**Comment by balraj-johal** [comment]
basic behaviour complete. could be improved through using the calculated mapping as an interpolation target rather than a direct call.

**Comment by andrewfstratton** [comment]
I tried adding this clip - and it failed to paste
