### ISSUE TITLE
Redesign access to Node Red

### ISSUE THREAD

**Issue by andrewfstratton** [andrewfstratton/quando#93]
Merge message passing
e.g.
![image](https://user-images.githubusercontent.com/10010895/61176564-bb83fc00-a5ba-11e9-8b44-fbafeb7db92a.png)

* Add menu
  * Put in broadcast (global - i.e. current mechanism) and Node-RED
  * browser/local/device/client/whatever can be added later
  * broadcast currently default - may need to be local later

**Comment by balraj-johal** [comment]
Functional blocks created, but need design consideration. Currently very similar to socket.io send message blocks. @DirectK
